### ISSUE TITLE
支持设置 static final变量的值-2.7版本支持

### ISSUE THREAD

**Issue by WangJi92** [WangJi92/arthas-idea-plugin#1]
### 问题来源
[问题设置static final](https://github.com/alibaba/arthas/issues/641)
### 解决思路
 通过ognl 反射处理，[参考java 反射 设置static final](https://www.cnblogs.com/noKing/p/9038234.html)

### 参数的值
```java
   private static final String  final_text ="1222222";
```
### ognl 的值得信息 ，这里没有进行final 重新加入，弹框编写不方便
```xml
ognl -x 3  '#field=@com.wj.study.demo.generator.ControllerTest@class.getDeclaredField("final_text"),#modifiers=#field.getClass().getDeclaredField("modifiers"),#modifiers.setAccessible(true),#modifiers.setInt(#field,#field.getModifiers() & ~@java.lang.reflect.Modifier@FINAL),#field.setAccessible(true),#field.set(null," 4444")' -c 18b4aac2
```
### 复杂的ognl 版本，没有使用这个放置在插件里面
```xml
ognl -x 3  '#field=@com.wj.study.demo.generator.ControllerTest@class.getDeclaredField("final_text"),#modifiers=#field.getClass().getDeclaredField("modifiers"),#modifiers.setAccessible(true),#modifiers.setInt(#field,#field.getModifiers() & ~@java.lang.reflect.Modifier@FINAL),#field.setAccessible(true),#field.set(null,"66666"),#modifiers.setInt(#field,#field.getModifiers()& ~@java.lang.reflect.Modifier@FINAL)' -c 18b4aac2
```
### arthas  idea 支持版本 2.7+

**Comment by starlai21** [comment]
![image](https://user-images.githubusercontent.com/13192545/128286894-7c08c144-c95e-495b-9dc0-eeff229578e1.png)
为什么还是无法设置 static  final 呢

**Comment by Destiny-jack-gif** [comment]
> ![image](https://user-images.githubusercontent.com/13192545/128286894-7c08c144-c95e-495b-9dc0-eeff229578e1.png) 为什么还是无法设置 static final 呢
我的也是这个问题，无法修改final变量

**Comment by WangJi92** [comment]
> ```
> @class.getDeclaredField
> ```

https://www.cnblogs.com/noKing/p/9038234.html  可以看看这篇文章
