### ISSUE TITLE
yuqu document 错别字？

### ISSUE THREAD

**Issue by anjia0532** [WangJi92/arthas-idea-plugin#106]
应该是 yuque document 吧？
![image](https://github.com/WangJi92/arthas-idea-plugin/assets/15098916/fc168fe1-2578-41d0-9e0c-45aa3d6b2cd5)

https://github.com/WangJi92/arthas-idea-plugin/blob/13039c77c473f6cecee9c294352173d41eab69b1/src/com/github/wangji92/arthas/plugin/ui/AppSettingsPage.form#L218

**Comment by WangJi92** [comment]
是的，可以提交个pr 修复一下

**Comment by anjia0532** [comment]
https://github.com/WangJi92/arthas-idea-plugin/pull/107
