### ISSUE TITLE
希望能出一个Arthas IDEA Plugin的Contribution说明

### ISSUE THREAD

**Issue by RaymondLam1** [WangJi92/arthas-idea-plugin#111]
下载代码后，发现和最新的IDEA插件开发有一定区别，希望能在README中提供开发者配置说明

**Comment by WangJi92** [comment]
应该没有什么区别，只是这里没有利用gradle进行管理,后续补充一下

**Comment by RaymondLam1** [comment]
> 应该没有什么区别，只是这里没有利用gradle进行管理,后续补充一下

是的，在打开源码后关于intellij的类都报红，这里需要在哪里设置一下呢？

**Comment by WangJi92** [comment]
> > 应该没有什么区别，只是这里没有利用gradle进行管理,后续补充一下
> 
> 是的，在打开源码后关于intellij的类都报红，这里需要在哪里设置一下呢？

这个不影响编译，这个是低版本IDEA API 接口，目前暂未适配高版本API，目前最新的idea ，都可以正常使用。
