### ISSUE TITLE
希望支持watch命令的条件参数. 

### ISSUE THREAD

**Issue by lingting** [WangJi92/arthas-idea-plugin#112]
可以加个专用选项, 然后弹框自己写就可以了.  能自动处理下 " 就更好了.

**Comment by lingting** [comment]
https://arthas.aliyun.com/doc/watch.html#%E6%9D%A1%E4%BB%B6%E8%A1%A8%E8%BE%BE%E5%BC%8F%E7%9A%84%E4%BE%8B%E5%AD%90

**Comment by WangJi92** [comment]
支持得不是很好，配置里面有一个配置可以生成 
Show the default conditional expression 1==1  

比如 ：
```java
watch org.springframework.boot.env.EnvironmentPostProcessor postProcessEnvironment '{params,returnObj,throwExp}'  -n 5  -x 3 '1==1'
```

然后自己在文本编辑器编辑也行，主要是大多数场景都是简单看一下，需要编辑过滤可以 文本处理一下。
