### ISSUE TITLE
通过静态SpringContent获取 Bean 报错，语法

### ISSUE THREAD

**Issue by MesmerizingXiaoSenSen** [WangJi92/arthas-idea-plugin#124]
![image](https://github.com/WangJi92/arthas-idea-plugin/assets/94464829/be22870f-fc00-4d3b-b64a-97adc16524a4)
多了一个点，在最后面，去掉就可以了
![image](https://github.com/WangJi92/arthas-idea-plugin/assets/94464829/d919756c-17bd-4d59-b62b-40e71d411ad6)

**Comment by WangJi92** [comment]
@MesmerizingXiaoSenSen  正常情况一下这个是访问方法上的 ，你估计放在类上面去了

**Comment by WangJi92** [comment]
暂未发布版本

**Comment by WangJi92** [comment]
@MesmerizingXiaoSenSen  已上线
