### ISSUE TITLE
希望idea中支持中文！！！

### ISSUE THREAD

**Issue by Chenbin1996** [WangJi92/arthas-idea-plugin#140]
对于我这种英文不太懂，对arthas不太熟悉的，中文看的更加迷糊了

**Comment by WangJi92** [comment]
查看官方教程，熟悉一下命令

sm  search method
sc   search clazz
watch  观察方法请求响应值
trace  观察方法调用链

arthas 在线教程也很完善 ，可以去看看 https://arthas.aliyun.com/

**Comment by WangJi92** [comment]
b 站也有教程，虽然版本比较早 但是理解差不多  https://www.bilibili.com/video/BV1yz4y1f7iz/?spm_id_from=333.999.0.0&vd_source=2d2b695c7a5bdb1e5d1fd26730df213e
