### ISSUE TITLE
为了兼容以前的版本，可以把新特性做成开关

### ISSUE THREAD

**Issue by chenshun00** [WangJi92/arthas-idea-plugin#18]
例如最新版本的-v，以前的arthas版本是没有的，加上这个就会报错。 

watch com.x.x.log.FullInfoBizLog FullInfoBizLog '{params,returnObj,throwExp}' `-v` -n 5 -x 3 '1==1'

**Comment by WangJi92** [comment]
先看一下自己的版本最新2.21 版本，这个特性在加入的时候就已经可以配置了，other settings 【Arthas Idea Plugin 】Print Condition Express Result 这个关闭即可 。更多查看视频 [arthas idea ](https://www.bilibili.com/video/BV1yz4y1f7iz/)
![image](https://user-images.githubusercontent.com/20874972/97822256-3ad99980-1cf0-11eb-8922-a7ce97b33459.png)
