### ISSUE TITLE
redefine 失败

### ISSUE THREAD

**Issue by molixiaoge** [WangJi92/arthas-idea-plugin#23]
生成redefine语句的时候失败,截图如下

![image](https://user-images.githubusercontent.com/1323533/103258391-b8a7e180-49cf-11eb-9be0-c2991b13a65d.png)

**Comment by WangJi92** [comment]
最初使用 replace("$","\\$") mac 没有问题  windows有问题 

https://blog.csdn.net/xrt95050/article/details/6651571 (替换$ 为 \$ )要把 $ 替换成 \$ ，则要使用 \\\\\\& 来替换，因为一个 \ 要使用 \\\ 来进行替换，而一个 $ 要使用 \\$ 来进行替换，因 \ 与  $ 在作为替换内容时都属于特殊字符：$ 字符表示反向引用组，而 \ 字符又是用来转义 $ 字符的.


为什么要转义 shell 脚本执行的时候这个字符特殊不能直接使用
当前类完整的路径中含有内部类$ 字符 ，不能再shell 中被解析要进行转义。

**Comment by WangJi92** [comment]
下个版本升级 改造掉
