### ISSUE TITLE
文档需要更新

### ISSUE THREAD

**Issue by yiding-he** [WangJi92/arthas-idea-plugin#33]
`toLowerFristChar` 应该是 `toLowerFirstChar` 的误写，并且在英语中，这个方法应该起名为 `uncapitalize`（参考[这里](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#uncapitalize-java.lang.String-)）。

**Comment by WangJi92** [comment]
@yiding-he 那你提交给pr 呀

**Comment by yiding-he** [comment]
> 
> 
> @yiding-he 那你提交给pr 呀

文档里面的截图应该是作者自己的项目，我是没有来源的。所以这个还得作者自己改正，要么换个其他的方法来演示。

**Comment by WangJi92** [comment]
那不改了,不影响
