### ISSUE TITLE
redefine失败,找不到class文件 

### ISSUE THREAD

**Issue by onnh** [WangJi92/arthas-idea-plugin#34]
环境：Windows 10 x64、gitbash(mintty 3.4.2)、idea 2020.02、arthas-idea-plugin 2.26
问题描述：在gitbash中执行脚本后，redefine语句提示class文件不存在。
可能原因：路径分隔符不同导致找不到指定文件。手动执行(redefine C:\\xxx\\xxx.class)成功，执行(redefine /c/xxx/xxx.class)失败找不到文件。
![image](https://user-images.githubusercontent.com/63949000/105470872-0f55c200-5cd5-11eb-9b0e-c3eadd616680.png)
![image](https://user-images.githubusercontent.com/63949000/105470992-37ddbc00-5cd5-11eb-84cc-c774a4bcbb0f.png)

**Comment by WangJi92** [comment]
@onnh 应该是文件路径不支持, 热更新命令只支持 mac  和 linux ,windows 这种场景不支持的。
