### ISSUE TITLE
java和mybatis热更新的脚本返回值问题

### ISSUE THREAD

**Issue by xuguoqin** [WangJi92/arthas-idea-plugin#75]
我在使用jenkins远程执行shell脚本的时候，获取不到报错的返回值，报错界面是error，但是通过shell命令的返回值还是0

**Comment by WangJi92** [comment]
Hello 没有get 到你的意思 ？

**Comment by xuguoqin** [comment]
就是热更新脚本执行redefineResult方法的时候，如果是error为什么不使用exit呢，这样即使报错了我的shell显示运行的结果返回值还是0

**Comment by WangJi92** [comment]
fix  https://github.com/WangJi92/arthas-idea-plugin/commit/c08f213c960bd0aea93d96d5052d9aac88c34abd
