### ISSUE TITLE
能不能再让人懒一点，加个ognl参数填充

### ISSUE THREAD

**Issue by ReZeroS** [WangJi92/arthas-idea-plugin#76]
如题，ognl取方法时，把参数用ui弹窗或者其他友好一点的方式（比如生成一个默认传参）等来填充

**Comment by ReZeroS** [comment]
现在好像也会填充一部分，但是好像默认参数是无参构造器，能不能抽出可以手动赋值（貌似这种场景更多？）

**Comment by WangJi92** [comment]
Hello  没有get 到，现在实现的方式 会默认生成 根据类型生成默认的参数的。

**Comment by ReZeroS** [comment]
感谢
