### ISSUE TITLE
idea插件提示“ this plugin is not a producton of JetBrains”

### ISSUE THREAD

**Issue by SokachWang** [WangJi92/arthas-idea-plugin#77]
idea插件提示“ this plugin is not a producton of JetBrains”，idea版本是2019.3.

**Comment by WangJi92** [comment]
> 

你是怎么安装的？没有遇到过

**Comment by SokachWang** [comment]
提示报错：“”Could not initialize class redis.clients.edis.HostAndPort”

**Comment by SokachWang** [comment]
提示：“Could not initialize class redis.clients.Jedis.HostAndPort”
