### ISSUE TITLE
容器内执行（Hot Swap）redefine热更新指令报错

### ISSUE THREAD

**Issue by handsometong** [WangJi92/arthas-idea-plugin#78]
<img width="1625" alt="image" src="https://user-images.githubusercontent.com/12708876/195046516-281d1468-8431-41b6-bab1-6c83e1daa899.png">

**Comment by WangJi92** [comment]
你手动执行一下 命令试一下呢？这个好像是 执行 as.sh --select       -c  这个失败了

**Comment by handsometong** [comment]
不行，报一样的错误，是Arthas的bug？

**Comment by handsometong** [comment]
> 你手动执行一下 命令试一下呢？这个好像是 执行 as.sh --select -c 这个失败了

不行，报一样的错误，是Arthas的bug

**Comment by WangJi92** [comment]
https://arthas.aliyun.com/doc/batch-support.html  试一下  ./as.sh -c 'sysprop; thread' <pid> > test.out

**Comment by WangJi92** [comment]
> > https://arthas.aliyun.com/doc/batch-support.html 试一下 ./as.sh -c 'sysprop; thread' > test.out
> 
> 执行为日志： <img alt="image" width="1107" src="https://user-images.githubusercontent.com/12708876/195743694-3924aad0-768a-4d3c-aef4-2a269eb8e0ab.png"> <img alt="image" width="993" src="https://user-images.githubusercontent.com/12708876/195743775-4291bfc0-6c71-40f8-a1c5-3a4fc16d1c0e.png">

你没有增加pid 看看 之前发的文档

**Comment by handsometong** [comment]
> ./as.sh -c 'sysprop; thread' > test.out
是这么加吗？加完输出内容还是一样
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/12708876/195777096-ce387686-bb56-43aa-84ca-0efe5fc1d612.png">

**Comment by WangJi92** [comment]
很像这个问题 你看看 @handsometong  https://arthas.aliyun.com/doc/faq.html#attach-docker-k8s-%E9%87%8C%E7%9A%84-pid-%E4%B8%BA-1-%E7%9A%84%E8%BF%9B%E7%A8%8B%E5%A4%B1%E8%B4%A5
