### ISSUE TITLE
如何远程连接？

### ISSUE THREAD

**Issue by zhenjia001** [WangJi92/arthas-idea-plugin#8]
插件只能arthas本机吗？意义不大吧，主要应该是远程主机可以配置化比较适合

**Comment by WangJi92** [comment]
目前Arthas 官方的工具还不够足够的简单，需要记住一些命令，特别是一些扩展性特别强的高级语法，比如ognl获取spring context 为所欲为，watch、trace 不够简单，需要构造一些命令工具的信息，因此只需要一个能够简单处理字符串信息的插件即可使用。当在处理线上问题的时候需要最快速、最便捷的命令，因此Idea arthas plugin插件还是有存在的意义和价值的。---这个是最初编写这个插件的最核心的理由。

这个插件的意义不是处理协议层面的问题，主要解决命令生成的问题，由于工程在idea 里面管理，你想想你要watch 哪个类，这个插件是知道的，帮助你更方便、更加快捷的构建命令。可以查看 [https://github.com/WangJi92/arthas-plugin-demo](https://github.com/WangJi92/arthas-plugin-demo)  可以体验一下这个demo

**Comment by WangJi92** [comment]
> 插件只能arthas本机吗？意义不大吧，主要应该是远程主机可以配置化比较适合

目前Arthas 官方的工具还不够足够的简单，需要记住一些命令，特别是一些扩展性特别强的高级语法，比如ognl获取spring context 为所欲为，watch、trace 不够简单，需要构造一些命令工具的信息，因此只需要一个能够简单处理字符串信息的插件即可使用。当在处理线上问题的时候需要最快速、最便捷的命令，因此Idea arthas plugin插件还是有存在的意义和价值的。---这个是最初编写这个插件的最核心的理由。

这个插件的意义不是处理协议层面的问题，主要解决命令生成的问题，由于工程在idea 里面管理，你想想你要watch 哪个类，这个插件是知道的，帮助你更方便、更加快捷的构建命令。可以查看 https://github.com/WangJi92/arthas-plugin-demo 可以体验一下这个demo
