### ISSUE TITLE
是否考虑对 Kotlin 的支持

### ISSUE THREAD

**Issue by butfool** [WangJi92/arthas-idea-plugin#83]
目前在 Kotlin 文件中大多数命令都是灰色的，但是其实一些命令可以像 Java 文件一样生成命令

**Comment by WangJi92** [comment]
不会考虑支持，可以参考 [idea 中如何 通过arthas idea plugin 查看 scala 文件 构建 arthas 命令](https://github.com/WangJi92/arthas-idea-plugin/issues/35)  Kotlin 最终会编译为class 文件，通过查看class文件生成命令，arthas idea  plugin 插件支持在class 文件中生生命令

**Comment by WangJi92** [comment]
我不是很懂 Kotlin ，反编译为.class 的文件 和 真实的差异,导致插件 不是所有的场景能够使用 和 scala 一样的
