### ISSUE TITLE
功能支持

### ISSUE THREAD

**Issue by kwepvbn** [WangJi92/arthas-idea-plugin#85]
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/126246019/221157049-64019963-4bad-420a-b0d5-fd3040d3a416.png">
你好， 由于服务是用Docker启动的， Docker容器image为openjdk:8u212-jdk， 是不带telnet及redis-cli的， 希望开发者能在使用剪切板功能时判断如无telnet工具， 可以选择是否强制执行。 不然docker里还需要再安装telnet命令。 这只是一个小小的建议哈~

**Comment by WangJi92** [comment]
@kwepvbn  as.sh 执行直接使用 https://arthas.aliyun.com/download/latest_version?mirror=aliyun 下载解压压缩包里面的，所有需求telnet 可以在镜像的里面追加一下，redis-cli 同理,不过这里使用 对象存储更加的方便点 ，支持aws 对象存储协议的都支持 。
