### ISSUE TITLE
2.40 版本 热更新报错 -Retransfrom 报错 illegalArgumentException

### ISSUE THREAD

**Issue by iiiHAVES** [WangJi92/arthas-idea-plugin#89]
2.40 版本 热更新报错

**Comment by iiiHAVES** [comment]
插件前几天不知道什么原因在idea中崩了，又重新下载回来，使用这个Retransfrom 一直报错。 配置的阿里云oss。 
![image](https://user-images.githubusercontent.com/51665641/226301649-defe81eb-e8b7-47f4-8e11-d266ed78c85b.png)

/root/opt/arthas/hotSwap/classes/hotSwapResult.out   
![image](https://user-images.githubusercontent.com/51665641/226307057-39931abb-7114-4999-9066-f571b137021a.png)

**Comment by iiiHAVES** [comment]
> @iiiHAVES 服务器 和本地的jdk 版本一致？ 整个流程感觉都正常呀

都是java8
服务器：openjdk version "1.8.0_242"
本机：java version "1.8.0_291"

我之前一直可以用的，突然不对劲了

**Comment by WangJi92** [comment]
这里是arthas 增强的代码  
![image](https://user-images.githubusercontent.com/20874972/226514291-03d1cf4b-5136-41d4-9cf0-6f9dabb7a91f.png)

 可以查看~/logs/arthas/ 目录下的日志 看看异常的堆栈信息

**Comment by zhoucanBa** [comment]
**
![image](https://user-images.githubusercontent.com/129197393/228295713-0db5f989-c8c0-48c2-a4ce-0119ee6f609b.png)
**

我也是一样的，之前都可以，重装idea后就不行了，中途也升级了这个插件

**Comment by iiiHAVES** [comment]
> ** ![image](https://user-images.githubusercontent.com/129197393/228295713-0db5f989-c8c0-48c2-a4ce-0119ee6f609b.png) ** ![image](https://user-images.githubusercontent.com/129197393/228296357-39bd807d-9401-4f93-91cb-98f3ccbe6259.png)
> 
> 我也是一样的，之前都可以，重装idea后就不行了，中途也升级了这个插件

后来有解决吗，会不会和插件在idea的残留配置文件有关

**Comment by zhoucanBa** [comment]
> 

我把插件降级到38这个版本就可以了，你也可以试试，不要用最新的40版本

**Comment by iiiHAVES** [comment]
> > 
> 
> 我把插件降级到38这个版本就可以了，你也可以试试，不要用最新的40版本

感谢提醒！刚刚试试降到38版本，热部署可以了。另外试了39版本也可以

**Comment by WangJi92** [comment]
> 试降到38版本，热部署可以了。另外试了39版本也可

2.40 这个版本有点问题，最新的2.41 已经修改ok了，你可以测试一下 @iiiHAVES

**Comment by iiiHAVES** [comment]
> > 试降到38版本，热部署可以了。另外试了39版本也可
> 
> 2.40 这个版本有点问题，最新的2.41 已经修改ok了，你可以测试一下 @iiiHAVES

刚刚更新到2.41，Retransfrom 功能正常了，👍👍👍
