### ISSUE TITLE
请确保已安装 JDK 并在 ~/.bashrc 里面配置 JAVA_HOME，此外必须存在 JAVA_HOME/lib/tools.jar

### ISSUE THREAD

**Issue by llingfeng** [WangJi92/arthas-idea-plugin#90]
macos版本：13.2.1
idea版本：IntelliJ IDEA 2022.1.1 (Ultimate Edition)

启动热部署服务出现报错：
Arthas 启动失败
请确保已安装 JDK 并在 ~/.bashrc 里面配置 JAVA_HOME，此外必须存在 JAVA_HOME/lib/tools.jar

macos系统里没有.bashrc文件，替代品是.zshrc文件。
检查了java环境是正常的，JAVA_HOME/lib/tools.jar这个文件是存在的。
本机在用户目录下新建了.bashrc文件也不行。

**Comment by WangJi92** [comment]
@llingfeng  you can check  [as.sh](https://github.com/alibaba/arthas/blob/master/bin/as.sh)  reset_for_env function

**Comment by llingfeng** [comment]
> @llingfeng you can check [as.sh](https://github.com/alibaba/arthas/blob/master/bin/as.sh) reset_for_env function

是不是目前不支持.zshrc的mac系统，是执行as.sh去重置java环境吗？试了下貌似没啥用，还是报之前的错误

**Comment by llingfeng** [comment]
@WangJi92 找到问题了，是先启动了应用观测功能，启动观测功能时会先kill掉原来的服务，然后重新生成一个命令启动应用服务，这个时候再去使用热部署功能选择上面启动的那个服务就会报错误。如果不启动观测功能，直接启动热部署服务就能链接上正常使用了。
