### ISSUE TITLE
希望结合 croc 实现热部署

### ISSUE THREAD

**Issue by Seifon** [WangJi92/arthas-idea-plugin#96]
croc是一款非常强大且方便的传输工具，希望可以采纳

目前base64的方案，并不是太可靠，因为浏览器控制台，无法粘贴大文本。如果结合croc传输工具，就非常方便了

另外如果用croc传输，就不要base64了

**Comment by WangJi92** [comment]
整体流程是怎么样的？ 现在使用对象存储服务挺方便，可以使用阿里云oss ，腾讯云，华为云，aws s3 等等都可以，无需安装什么；
base64确实不够OK；

**Comment by Seifon** [comment]
> 整体流程是怎么样的？ 现在使用对象存储服务挺方便，可以使用阿里云oss ，腾讯云，华为云，aws s3 等等都可以，无需安装什么； base64确实不够OK；

OSS的方式，真的没有croc这款工具方便，可以了解一下

**Comment by Seifon** [comment]
https://github.com/schollz/croc

**Comment by WangJi92** [comment]
![image](https://user-images.githubusercontent.com/20874972/236092145-363872f7-ade6-484d-9791-69d1dab9c6a2.png)

----
上面是 目前的执行流程，执行脚本存储到中介服务。可以是redis、对象存储、剪切板(执行脚本base64)等存储中介。

整体目标是: 简单、轻量、尽量减少执行的步骤；(ps：这里没有直接配置登录服务器的相关信息、直接一口气执行远程服务器，整体方案实现有点复杂，且不是所有的环境都支持)

看了一下 croc 的方案：本地需要执行脚本文件，可以考虑将执行脚本文件生成出来放置到本地环境，然后开发者自己去处理文件上传到目标服务器，整体流程稍微有点长，最推荐还是对象存储服务。
